// AUTO-GENERATED by scripts/sync-claude-designs.mjs from data/labs/*.json
// Do not edit by hand. Edit the JSON files and re-run `npm run sync:designs`.
// Re-upload this file to your Claude Designs project after each sync.
export const DESIGN_TOKENS = {
  "core": {
    "id": "core",
    "name": "AI Mindset {core}",
    "eyebrow": "AI MINDSET · EVERGREEN",
    "title": "ai mindset",
    "accentTitle": "{core}",
    "accent": "#a78bfa",
    "accentRgb": "167,139,250",
    "accentName": "core mauve",
    "secondaryAccent": "#fbbf24",
    "secondaryAccentRgb": "251,191,36",
    "recordPaletteLegend": "evergreen — single mauve accent for cross-cohort content",
    "photoBase": "./speakers",
    "dates": "evergreen",
    "footer": "aimindset.org",
    "sub": "evergreen brand · workshops · founder os · communities · cross-cohort content",
    "fonts": {
      "mono": "'JetBrains Mono', monospace",
      "display": "'IBM Plex Mono', monospace",
      "googleFontsHref": "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600;700&display=swap"
    },
    "weekAccents": {
      "W1": "#a78bfa",
      "W2": "#60a5fa",
      "W3": "#4ade80",
      "W4": "#fbbf24"
    },
    "featuredIds": [],
    "defaultFormats": {
      "generic": "wide",
      "speaker": "wide",
      "org": "wide"
    },
    "formatStyles": {
      "generic": {
        "wide": [
          "field",
          "mosaic",
          "roster",
          "cards"
        ],
        "square": [
          "mosaic",
          "stack",
          "board"
        ],
        "carousel": [
          "manifesto",
          "headline",
          "splash"
        ]
      },
      "speaker": {
        "wide": [
          "aimnative",
          "surname"
        ],
        "square": [
          "portrait",
          "quote",
          "signal"
        ],
        "story": [
          "story",
          "story-card",
          "story-poster"
        ],
        "carousel": [
          "manifesto"
        ]
      },
      "org": {
        "wide": [
          "plaque",
          "poster",
          "rail",
          "digest"
        ],
        "square": [
          "panel",
          "orbit"
        ]
      }
    },
    "genericStyles": [
      "field",
      "mosaic",
      "roster",
      "cards"
    ],
    "speakerStyles": [
      "aimnative",
      "surname"
    ],
    "orgStyles": [
      "plaque",
      "poster",
      "rail",
      "digest"
    ]
  },
  "s3": {
    "id": "s3",
    "name": "AI-Native Sprint S3",
    "eyebrow": "AI Mindset × CybOS",
    "title": "ai-native sprint",
    "accentTitle": "{s3}",
    "accent": "#8ddff2",
    "accentRgb": "141,223,242",
    "accentName": "s3 blue",
    "secondaryAccent": "#f0b84b",
    "secondaryAccentRgb": "240,184,75",
    "recordPaletteLegend": "host cyan · practice amber · guest blue",
    "family": "ainative",
    "photoBase": "./speakers-ainative",
    "dates": "2 MAY – 25 MAY 2026",
    "footer": "ai-native.aimindset.org",
    "sub": "4 weeks · setup / systems / vertical focus · curators + guest speakers + closing artifacts",
    "fonts": {
      "mono": "'IBM Plex Mono', monospace",
      "display": "'Space Grotesk', sans-serif",
      "googleFontsHref": "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap"
    },
    "weekAccents": {
      "W1": "#4dc9d4",
      "W2": "#38d9a9",
      "W3": "#ff3b8b",
      "W4": "#fcbb00"
    },
    "featuredIds": [
      "sereja-ris",
      "stepan-gershuni",
      "denis-smirnov",
      "seva-ustinov",
      "alexander-povaliaev"
    ],
    "heroId": "sereja-ris",
    "defaultFormats": {
      "generic": "wide",
      "speaker": "wide",
      "org": "wide"
    },
    "formatStyles": {
      "generic": {
        "wide": [
          "field",
          "mosaic",
          "roster",
          "cards"
        ],
        "square": [
          "mosaic",
          "stack",
          "board"
        ],
        "carousel": [
          "manifesto",
          "headline",
          "splash"
        ]
      },
      "speaker": {
        "wide": [
          "aimnative",
          "surname"
        ],
        "square": [
          "portrait",
          "quote",
          "signal"
        ],
        "story": [
          "story",
          "story-card",
          "story-poster"
        ],
        "carousel": [
          "manifesto"
        ]
      },
      "org": {
        "wide": [
          "plaque",
          "poster",
          "rail",
          "digest"
        ],
        "square": [
          "panel",
          "orbit"
        ]
      }
    },
    "genericStyles": [
      "field",
      "mosaic",
      "roster",
      "cards"
    ],
    "speakerStyles": [
      "aimnative",
      "surname"
    ],
    "orgStyles": [
      "plaque",
      "poster",
      "rail",
      "digest"
    ]
  },
  "x26": {
    "id": "x26",
    "name": "Spring Lab {x26}",
    "eyebrow": "AI MINDSET · SPRING LAB X26",
    "title": "spring lab",
    "accentTitle": "{x26}",
    "accent": "#16a34a",
    "accentRgb": "22,163,74",
    "accentName": "x26 green",
    "secondaryAccent": "#fbbf24",
    "secondaryAccentRgb": "251,191,36",
    "recordPaletteLegend": "W1 gold · W2 violet · W3 blue · W4 green",
    "photoBase": "./speakers",
    "dates": "27 APR – 25 MAY 2026",
    "footer": "x26 / spring / batch:03",
    "sub": "4 weeks · text / image / audio / code · workshops + focus + creative shipping",
    "fonts": {
      "mono": "'Space Mono', monospace",
      "display": "'Space Grotesk', sans-serif",
      "googleFontsHref": "https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Space+Grotesk:wght@500;600;700&display=swap"
    },
    "weekAccents": {
      "W1": "#fbbf24",
      "W2": "#a78bfa",
      "W3": "#60a5fa",
      "W4": "#4ade80"
    },
    "featuredIds": [
      "anca-stavenski",
      "arseny-popov",
      "olya-eremina",
      "tonya-zhukova",
      "ilya-gindin",
      "sereja-ris",
      "nomusicians",
      "oleg-tserbaev",
      "evgeniy-volnov",
      "stanislav-glazov",
      "alexander-povaliaev"
    ],
    "defaultFormats": {
      "generic": "wide",
      "speaker": "wide",
      "org": "wide"
    },
    "formatStyles": {
      "generic": {
        "wide": [
          "field",
          "mosaic",
          "roster",
          "dense",
          "strips",
          "cards"
        ],
        "square": [
          "mosaic",
          "stack",
          "board"
        ],
        "carousel": [
          "manifesto",
          "headline",
          "splash"
        ]
      },
      "speaker": {
        "wide": [
          "aimnative",
          "surname"
        ],
        "square": [
          "portrait",
          "quote",
          "signal"
        ],
        "story": [
          "story",
          "story-card",
          "story-poster"
        ],
        "carousel": [
          "manifesto"
        ]
      },
      "org": {
        "wide": [
          "plaque",
          "poster",
          "rail",
          "digest"
        ],
        "square": [
          "panel",
          "orbit"
        ]
      }
    },
    "genericStyles": [
      "field",
      "mosaic",
      "roster",
      "dense",
      "strips",
      "cards"
    ],
    "speakerStyles": [
      "aimnative",
      "surname",
      "portrait",
      "quote",
      "signal",
      "story",
      "story-card",
      "story-poster"
    ],
    "orgStyles": [
      "plaque",
      "poster",
      "rail",
      "digest",
      "panel",
      "orbit"
    ]
  }
};

export function getLab(id) {
  return DESIGN_TOKENS[id] || DESIGN_TOKENS.core;
}

export function tokenToCssVars(lab) {
  if (!lab) return {};
  return {
    '--accent': lab.accent,
    '--accent-rgb': lab.accentRgb,
    '--accent-name': lab.accentName,
    '--secondary-accent': lab.secondaryAccent,
    '--secondary-accent-rgb': lab.secondaryAccentRgb,
    '--font-mono': lab.fonts && lab.fonts.mono,
    '--font-display': lab.fonts && lab.fonts.display,
    '--week-1': lab.weekAccents && lab.weekAccents.W1,
    '--week-2': lab.weekAccents && lab.weekAccents.W2,
    '--week-3': lab.weekAccents && lab.weekAccents.W3,
    '--week-4': lab.weekAccents && lab.weekAccents.W4,
  };
}

export default DESIGN_TOKENS;
