#!/usr/bin/env node
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

function resolveRefs(node, root) {
  if (typeof node === 'string') {
    const m = node.match(/^\{([\w.-]+)\}$/);
    if (!m) return node;
    const path = m[1].split('.');
    let cur = root;
    for (const p of path) cur = cur?.[p];
    if (cur && '$value' in cur) return resolveRefs(cur.$value, root);
    return cur;
  }
  if (Array.isArray(node)) return node.map(n => resolveRefs(n, root));
  if (node && typeof node === 'object') {
    const out = {};
    for (const k of Object.keys(node)) out[k] = resolveRefs(node[k], root);
    return out;
  }
  return node;
}

function flattenTokens(layers) {
  // layers: { primitive, semantic, component } — merge in order
  const merged = { ...layers.primitive, ...layers.semantic, ...layers.component };
  return resolveRefs(merged, merged);
}

const here = dirname(fileURLToPath(import.meta.url));
const labsDir = resolve(here, '..', 'data', 'labs');
const tokensDir = resolve(here, '..', 'data', 'tokens');
const outFile = resolve(here, '..', 'data', 'labs.bundle.js');

const primitive = JSON.parse(readFileSync(resolve(tokensDir, 'primitive.json'), 'utf8'));
const semantic  = JSON.parse(readFileSync(resolve(tokensDir, 'semantic.json'),  'utf8'));
const component = JSON.parse(readFileSync(resolve(tokensDir, 'component.json'), 'utf8'));
const baseTokens = flattenTokens({ primitive, semantic, component });

const labs = {};
for (const file of readdirSync(labsDir)) {
  if (!file.endsWith('.json')) continue;
  const id = file.replace(/\.json$/, '');
  const labOverlay = JSON.parse(readFileSync(resolve(labsDir, file), 'utf8'));
  const finalTokens = { ...baseTokens, ...labOverlay };
  labs[id] = finalTokens;
}

const banner = `// AUTO-GENERATED by scripts/build-labs.mjs from data/labs/*.json
// Do not edit by hand. Edit the JSON files and re-run \`npm run build:labs\`.
`;

const body = `(function (root) {
  const tokens = ${JSON.stringify(labs, null, 2)};
  root.AIMStudioLabTokens = tokens;
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = tokens;
  }
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;

writeFileSync(outFile, banner + body, 'utf8');
console.log(`[build-labs] wrote ${outFile} with labs: ${Object.keys(labs).join(', ')}`);
