#!/usr/bin/env node
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const labsDir = resolve(here, '..', 'data', 'labs');
const outFile = resolve(here, '..', 'data', 'labs.bundle.js');

const labs = {};
for (const file of readdirSync(labsDir)) {
  if (!file.endsWith('.json')) continue;
  const id = file.replace(/\.json$/, '');
  const content = JSON.parse(readFileSync(resolve(labsDir, file), 'utf8'));
  labs[id] = content;
}

const banner = `// AUTO-GENERATED by scripts/build-labs.mjs from data/labs/*.json
// Do not edit by hand. Edit the JSON files and re-run \`npm run build:labs\`.
`;

const body = `(function (root) {
  const tokens = ${JSON.stringify(labs, null, 2)};
  root.AIMStudioLabTokens = tokens;
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = tokens;
  }
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;

writeFileSync(outFile, banner + body, 'utf8');
console.log(`[build-labs] wrote ${outFile} with labs: ${Object.keys(labs).join(', ')}`);
